name: Winter Garden
favicon: null
layout_spectrum: 0.34523
typography_spectrum: 0.66547
title: 'Winter Garden BioSciences '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebeff8'
    - '#0f140d'
    - '#2e441d'
    - '#7aa114'
    - '#b0dd46'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.5848509310744703
  rhythmicContrast: 0.6898281280882657
purpose: []
